package seedgen

import (
	"fmt"
	"io"
	"strings"
)

type Options struct {
	Rows           int
	DaysPerListing int
	StartDayOffset int
	Prefix         string
}

func (o Options) Normalized() Options {
	if o.Rows <= 0 {
		o.Rows = 100
	}
	if o.DaysPerListing <= 0 {
		o.DaysPerListing = min(o.Rows, 30)
	}
	if o.DaysPerListing < 2 {
		o.DaysPerListing = 2
	}
	if o.StartDayOffset <= 0 {
		o.StartDayOffset = 120
	}
	if strings.TrimSpace(o.Prefix) == "" {
		o.Prefix = "load"
	}
	return o
}

func Generate(w io.Writer, options Options) error {
	o := options.Normalized()
	if o.Rows > 9_999_999 {
		return fmt.Errorf("rows must be <= 9999999 to keep generated phone numbers unique")
	}

	writeHeader(w, o)
	writeUsers(w, o)
	writeUserRoles(w, o)
	writeAddresses(w, o)
	writeListings(w, o)
	writePhotos(w, o)
	writeListingPhotos(w, o)
	writeBasePrices(w, o)
	writeAvailability(w, o)
	writeBookingPlan(w, o)
	writeBookings(w, o)
	writePayments(w)
	writeReviews(w)
	writePriceHistoryTriggerData(w, o)
	_, err := fmt.Fprintln(w, "COMMIT;")
	return err
}

func writeHeader(w io.Writer, o Options) {
	fmt.Fprintf(w, "-- Generated by rentalctl seedgen\n")
	fmt.Fprintf(w, "-- rows=%d days_per_listing=%d start_day_offset=%d prefix=%s\n\n", o.Rows, o.DaysPerListing, o.StartDayOffset, o.Prefix)
	fmt.Fprintln(w, "SET search_path = application, public;")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "BEGIN;")
	fmt.Fprintln(w)
}

func writeUsers(w io.Writer, o Options) {
	fmt.Fprintln(w, "INSERT INTO users (username, phone_number, email, status)")
	fmt.Fprintln(w, "VALUES")
	for i := 1; i <= o.Rows; i++ {
		fmt.Fprintf(w, "    (%s, %s, %s, 'active')%s\n",
			q(ownerName(o, i)),
			q(fmt.Sprintf("+2888%07d", i)),
			q(ownerName(o, i)+"@example.com"),
			comma(i, o.Rows*2))
	}
	for i := 1; i <= o.Rows; i++ {
		item := o.Rows + i
		fmt.Fprintf(w, "    (%s, %s, %s, 'active')%s\n",
			q(guestName(o, i)),
			q(fmt.Sprintf("+2999%07d", i)),
			q(guestName(o, i)+"@example.com"),
			comma(item, o.Rows*2))
	}
	fmt.Fprintln(w, "ON CONFLICT (username) DO NOTHING;")
	fmt.Fprintln(w)
}

func writeUserRoles(w io.Writer, o Options) {
	fmt.Fprintf(w, `INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
         JOIN roles r ON r.name = 'owner'
WHERE u.username LIKE %s
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
         JOIN roles r ON r.name = 'guest'
WHERE u.username LIKE %s
ON CONFLICT DO NOTHING;

`, q(o.Prefix+"_owner_%"), q(o.Prefix+"_guest_%"))
}

func writeAddresses(w io.Writer, o Options) {
	cities := []struct {
		country string
		city    string
	}{
		{"US", "New York"},
		{"US", "San Francisco"},
		{"DE", "Berlin"},
		{"RU", "Moscow"},
		{"FR", "Paris"},
		{"GB", "London"},
		{"ES", "Barcelona"},
		{"IT", "Rome"},
	}

	fmt.Fprintln(w, "WITH seed(idx, country_code, city_name, street_line1, street_line2, region, postal_code, link) AS (")
	fmt.Fprintln(w, "    VALUES")
	for i := 1; i <= o.Rows; i++ {
		city := cities[(i-1)%len(cities)]
		fmt.Fprintf(w, "        (%d, %s, %s, %s, %s, 'LOAD', %s, %s)%s\n",
			i,
			q(city.country),
			q(city.city),
			q(fmt.Sprintf("Load Street %d", i)),
			q(fmt.Sprintf("Load Building %d", (i%50)+1)),
			q(fmt.Sprintf("%06d", 10000+i)),
			q(fmt.Sprintf("https://maps.example/%s-%d", o.Prefix, i)),
			comma(i, o.Rows))
	}
	fmt.Fprint(w, `)
INSERT INTO addresses (city_id, street_line1, street_line2, region, postal_code, link)
SELECT c.id, s.street_line1, s.street_line2, s.region, s.postal_code, s.link
FROM seed s
         JOIN countries co ON co.code = s.country_code
         JOIN cities c ON c.country_id = co.id AND c.name = s.city_name
WHERE NOT EXISTS (
    SELECT 1
    FROM addresses a
    WHERE a.city_id = c.id
      AND a.street_line1 = s.street_line1
);
`)
}

func writeListings(w io.Writer, o Options) {
	objectTypes := []string{"apartment", "house", "studio", "loft", "villa", "townhouse"}

	fmt.Fprintln(w, "WITH seed(idx, owner_username, object_type_name, street_line1, capacity, rooms, description) AS (")
	fmt.Fprintln(w, "    VALUES")
	for i := 1; i <= o.Rows; i++ {
		fmt.Fprintf(w, "        (%d, %s, %s, %s, %d, %d, %s)%s\n",
			i,
			q(ownerName(o, i)),
			q(objectTypes[(i-1)%len(objectTypes)]),
			q(fmt.Sprintf("Load Street %d", i)),
			(i%6)+1,
			(i%4)+1,
			q(listingDescription(o, i)),
			comma(i, o.Rows))
	}
	fmt.Fprint(w, `)
INSERT INTO listings (owner_id, object_type_id, address_id, capacity, number_of_rooms, description, status)
SELECT u.id, ot.id, a.id, s.capacity, s.rooms, s.description, 'active'
FROM seed s
         JOIN users u ON u.username = s.owner_username
         JOIN object_types ot ON ot.name = s.object_type_name
         JOIN addresses a ON a.street_line1 = s.street_line1
WHERE NOT EXISTS (
    SELECT 1
    FROM listings l
    WHERE l.description = s.description
);
`)
}

func writePhotos(w io.Writer, o Options) {
	fmt.Fprintln(w, "INSERT INTO photos (extension, link)")
	fmt.Fprintln(w, "VALUES")
	for i := 1; i <= o.Rows; i++ {
		extension := "png"
		if i%2 == 0 {
			extension = "jpeg"
		}
		fmt.Fprintf(w, "    (%s, %s)%s\n",
			q(extension),
			q(fmt.Sprintf("https://images.example/%s-listing-%d.img", o.Prefix, i)),
			comma(i, o.Rows))
	}
	fmt.Fprintln(w, "ON CONFLICT (link) DO NOTHING;")
	fmt.Fprintln(w)
}

func writeListingPhotos(w io.Writer, o Options) {
	fmt.Fprintln(w, "WITH seed(listing_description, photo_link, slot) AS (")
	fmt.Fprintln(w, "    VALUES")
	for i := 1; i <= o.Rows; i++ {
		fmt.Fprintf(w, "        (%s, %s, 1)%s\n",
			q(listingDescription(o, i)),
			q(fmt.Sprintf("https://images.example/%s-listing-%d.img", o.Prefix, i)),
			comma(i, o.Rows))
	}
	fmt.Fprint(w, `)
INSERT INTO listing_photos (listing_id, photo_id, slot)
SELECT l.id, p.id, s.slot
FROM seed s
         JOIN listings l ON l.description = s.listing_description
         JOIN photos p ON p.link = s.photo_link
ON CONFLICT DO NOTHING;
`)
}

func writeBasePrices(w io.Writer, o Options) {
	currencies := []string{"USD", "EUR", "GBP", "RUB"}

	fmt.Fprintln(w, "WITH seed(currency_code, amount_in_minor, listing_description) AS (")
	fmt.Fprintln(w, "    VALUES")
	for i := 1; i <= o.Rows; i++ {
		fmt.Fprintf(w, "        (%s, %d, %s)%s\n",
			q(currencies[(i-1)%len(currencies)]),
			10000+(i%9000),
			q(listingDescription(o, i)),
			comma(i, o.Rows))
	}
	fmt.Fprint(w, `)
INSERT INTO base_prices (currency_id, amount_in_minor, listing_id)
SELECT c.id, s.amount_in_minor, l.id
FROM seed s
         JOIN currencies c ON c.code = s.currency_code
         JOIN listings l ON l.description = s.listing_description
ON CONFLICT (listing_id) DO UPDATE
    SET currency_id = EXCLUDED.currency_id,
        amount_in_minor = EXCLUDED.amount_in_minor,
        last_update_date = now();
`)
}

func writeAvailability(w io.Writer, o Options) {
	total := o.Rows * o.DaysPerListing
	fmt.Fprintln(w, "WITH seed(listing_description, day_offset) AS (")
	fmt.Fprintln(w, "    VALUES")
	index := 0
	for listing := 1; listing <= o.Rows; listing++ {
		for day := 1; day <= o.DaysPerListing; day++ {
			index++
			fmt.Fprintf(w, "        (%s, %d)%s\n",
				q(listingDescription(o, listing)),
				o.StartDayOffset+day,
				comma(index, total))
		}
	}
	fmt.Fprint(w, `)
INSERT INTO listing_availability_days (available_date, status, listing_id)
SELECT (current_date + s.day_offset)::date, 'available', l.id
FROM seed s
         JOIN listings l ON l.description = s.listing_description
ON CONFLICT (listing_id, available_date) DO NOTHING;
`)
}

func writeBookingPlan(w io.Writer, o Options) {
	fmt.Fprint(w, `CREATE TEMP TABLE seedgen_booking_plan
(
    plan_id               BIGINT PRIMARY KEY,
    listing_description   TEXT           NOT NULL,
    day_offset            INT            NOT NULL,
    guest_username        TEXT           NOT NULL,
    currency_code         TEXT           NOT NULL,
    amount_in_minor       BIGINT         NOT NULL,
    target_status         booking_status NOT NULL,
    cancelled_by_username TEXT,
    cancellation_reason   TEXT,
    booking_id            BIGINT
);
`)

	statuses := []string{"completed", "confirmed", "payment_pending", "created", "cancelled", "expired"}
	planID := 0
	plansTotal := o.Rows * (o.DaysPerListing / 2)
	fmt.Fprintln(w, "INSERT INTO seedgen_booking_plan (plan_id, listing_description, day_offset, guest_username, currency_code, amount_in_minor, target_status, cancelled_by_username, cancellation_reason)")
	fmt.Fprintln(w, "VALUES")
	for listing := 1; listing <= o.Rows; listing++ {
		for day := 2; day <= o.DaysPerListing; day += 2 {
			planID++
			status := statuses[(listing+day)%len(statuses)]
			guestIndex := ((listing + day - 2) % o.Rows) + 1
			amount := 10000 + (listing % 9000) + ((listing + day) % 5 * 100)
			cancelledBy := "NULL"
			reason := "NULL"
			if status == "cancelled" {
				if (listing+day)%2 == 0 {
					cancelledBy = q(guestName(o, guestIndex))
					reason = q("guest changed plans (load)")
				} else {
					cancelledBy = q(ownerName(o, listing))
					reason = q("owner maintenance issue (load)")
				}
			}
			fmt.Fprintf(w, "    (%d, %s, %d, %s, %s, %d, %s, %s, %s)%s\n",
				planID,
				q(listingDescription(o, listing)),
				o.StartDayOffset+day,
				q(guestName(o, guestIndex)),
				q(currencyForListing(listing)),
				amount,
				q(status),
				cancelledBy,
				reason,
				comma(planID, plansTotal))
		}
	}
	fmt.Fprintln(w, ";")
	fmt.Fprintln(w)
}

func writeBookings(w io.Writer, o Options) {
	fmt.Fprint(w, `INSERT INTO bookings
(listing_id,
 created_by_user_id,
 guests_count,
 total_amount_currency_id,
 total_amount_in_minor,
 status,
 cancelled_by_user_id,
 cancellation_reason,
 booking_expires_at)
SELECT l.id,
       guest.id,
       ((p.plan_id % 4) + 1)::int,
       c.id,
       p.amount_in_minor,
       CASE
           WHEN p.target_status IN ('confirmed', 'completed') THEN 'confirmed'::booking_status
           WHEN p.target_status = 'payment_pending' THEN 'payment_pending'::booking_status
           ELSE 'created'::booking_status
           END,
       NULL,
       NULL,
       now() + interval '4 minutes' + ((p.plan_id % 1000000)::text || ' microseconds')::interval
FROM seedgen_booking_plan p
         JOIN listings l ON l.description = p.listing_description
         JOIN users guest ON guest.username = p.guest_username
         JOIN currencies c ON c.code = p.currency_code;

UPDATE seedgen_booking_plan p
SET booking_id = b.id
FROM bookings b
         JOIN listings l ON l.id = b.listing_id
         JOIN users guest ON guest.id = b.created_by_user_id
WHERE l.description = p.listing_description
  AND guest.username = p.guest_username
  AND b.booking_expires_at = now() + interval '4 minutes' + ((p.plan_id % 1000000)::text || ' microseconds')::interval
  AND b.total_amount_in_minor = p.amount_in_minor;

INSERT INTO booking_days (booking_id, availability_day_id, listing_id)
SELECT p.booking_id, d.id, l.id
FROM seedgen_booking_plan p
         JOIN listings l ON l.description = p.listing_description
         JOIN listing_availability_days d
              ON d.listing_id = l.id
             AND d.available_date = (current_date + p.day_offset)::date
WHERE p.booking_id IS NOT NULL
ON CONFLICT DO NOTHING;

UPDATE bookings b
SET status = p.target_status,
    cancelled_by_user_id = cancel_user.id,
    cancellation_reason = p.cancellation_reason,
    last_update_date = now()
FROM seedgen_booking_plan p
         LEFT JOIN users cancel_user ON cancel_user.username = p.cancelled_by_username
WHERE b.id = p.booking_id
  AND b.status IS DISTINCT FROM p.target_status;

UPDATE listing_availability_days d
SET status = CASE
                 WHEN p.target_status IN ('completed', 'confirmed') THEN 'booked'::availability_status
                 WHEN p.target_status IN ('created', 'payment_pending') THEN 'held'::availability_status
                 ELSE 'available'::availability_status
             END,
    last_update_date = now()
FROM seedgen_booking_plan p
         JOIN listings l ON l.description = p.listing_description
WHERE d.listing_id = l.id
  AND d.available_date = (current_date + p.day_offset)::date
  AND p.booking_id IS NOT NULL;
`)
}

func writePayments(w io.Writer) {
	fmt.Fprint(w, `INSERT INTO payments
(booking_id,
 currency_id,
 amount_in_minor,
 refunded_amount_in_minor,
 status,
 provider_payment_session_id,
 provider_payment_session_expires_at)
SELECT p.booking_id,
       c.id,
       p.amount_in_minor,
       CASE
           WHEN p.target_status = 'confirmed' AND (p.plan_id % 5) = 0 THEN p.amount_in_minor / 3
           WHEN p.target_status = 'cancelled' AND (p.plan_id % 3) = 0 THEN p.amount_in_minor
           ELSE 0
           END,
       CASE
           WHEN p.target_status = 'completed' THEN 'paid'::payment_status
           WHEN p.target_status = 'confirmed' AND (p.plan_id % 5) = 0 THEN 'partially_refunded'::payment_status
           WHEN p.target_status = 'confirmed' THEN 'paid'::payment_status
           WHEN p.target_status IN ('payment_pending', 'created') THEN 'initiated'::payment_status
           WHEN p.target_status = 'cancelled' AND (p.plan_id % 3) = 0 THEN 'refunded'::payment_status
           WHEN p.target_status = 'cancelled' THEN 'cancelled'::payment_status
           ELSE 'expired'::payment_status
           END,
       'load-payment-' || p.booking_id,
       now() + interval '5 minutes'
FROM seedgen_booking_plan p
         JOIN currencies c ON c.code = p.currency_code
WHERE p.booking_id IS NOT NULL
  AND NOT (p.target_status = 'created' AND (p.plan_id % 2) = 1)
ON CONFLICT (booking_id) DO NOTHING;
`)
}

func writeReviews(w io.Writer) {
	fmt.Fprint(w, `INSERT INTO reviews (booking_id, mark, body, moderated)
SELECT p.booking_id,
       ((p.plan_id % 5) + 1)::smallint,
       'Load review for booking ' || p.booking_id,
       false
FROM seedgen_booking_plan p
WHERE p.booking_id IS NOT NULL
  AND p.target_status = 'completed'
ON CONFLICT (booking_id) DO NOTHING;
`)
}

func writePriceHistoryTriggerData(w io.Writer, o Options) {
	fmt.Fprintf(w, `UPDATE base_prices bp
SET amount_in_minor = bp.amount_in_minor + 111,
    last_update_date = now()
FROM listings l
WHERE bp.listing_id = l.id
  AND l.description LIKE %s
  AND (l.id %% 10 = 0);

`, q(listingDescriptionPattern(o)))
}

func ownerName(o Options, i int) string {
	return fmt.Sprintf("%s_owner_%d", o.Prefix, i)
}

func guestName(o Options, i int) string {
	return fmt.Sprintf("%s_guest_%d", o.Prefix, i)
}

func listingDescription(o Options, i int) string {
	if o.Prefix == "load" {
		return fmt.Sprintf("Load listing #%d", i)
	}
	return fmt.Sprintf("%s listing #%d", o.Prefix, i)
}

func listingDescriptionPattern(o Options) string {
	if o.Prefix == "load" {
		return "Load listing #%"
	}
	return o.Prefix + " listing #%"
}

func currencyForListing(i int) string {
	currencies := []string{"USD", "EUR", "GBP", "RUB"}
	return currencies[(i-1)%len(currencies)]
}

func q(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func comma(index int, total int) string {
	if index == total {
		return ""
	}
	return ","
}
