# Настройки delayed physical standby с задержкой применения WAL.
data_directory = '/var/lib/postgresql/18/docker'
listen_addresses = '*'
unix_socket_directories = '/var/run/postgresql'
hba_file = '/etc/postgresql/physical-delayed/pg_hba.conf'

hot_standby = on
primary_slot_name = 'rental_physical_delayed_slot'
recovery_min_apply_delay = '5min'
