# Локальный административный доступ внутри контейнера logical subscriber.
local   all             all                                     trust

# Клиентские подключения к logical subscriber.
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
host    all             all             0.0.0.0/0               scram-sha-256
