# Настройки logical subscriber-кластера.
data_directory = '/var/lib/postgresql/18/docker'
listen_addresses = '*'
unix_socket_directories = '/var/run/postgresql'
hba_file = '/etc/postgresql/logical-subscriber/pg_hba.conf'

max_logical_replication_workers = 4
max_sync_workers_per_subscription = 2
