# Настройки быстрой physical standby без искусственной задержки.
data_directory = '/var/lib/postgresql/18/docker'
listen_addresses = '*'
unix_socket_directories = '/var/run/postgresql'
hba_file = '/etc/postgresql/physical-fast/pg_hba.conf'

hot_standby = on
primary_slot_name = 'rental_physical_fast_slot'
