# Настройки primary-кластера, относящиеся к репликации.
data_directory = '/var/lib/postgresql/18/docker'
listen_addresses = '*'
unix_socket_directories = '/var/run/postgresql'
hba_file = '/etc/postgresql/primary/pg_hba.conf'

wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
